### ISSUE TITLE
Api Key

### ISSUE THREAD

**Issue by guigui91** [abulte/transilien#1]
Hello, how did you get the api key? I made a request by email and no return. On another page I can only get the SNCF API key.
Thank you

**Comment by abulte** [comment]
Hi! It was a loooong time ago but I remember sending an email to an address I found online and getting a response.

**Comment by gvivat** [comment]
> Hello, how did you get the api key? I made a request by email and no return. On another page I can only get the SNCF API key. Thank you

Hi there, i'm too in need of the api key and i did way too much request to their email adrress.
Did you find a way to get the api key ?
